name: Detect Changes and Publish Plugins to NPM

on:
  push:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed_plugins: ${{ steps.filter_changes.outputs.plugins }}

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identificar e filtrar pacotes válidos alterados
        id: filter_changes
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            CHANGED_FILES=$(git ls-files)
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
          ALL_PACKAGE_DIRS=$(find plugins -name "package.json" -exec dirname {} \; | sort -u)
          VALID_PLUGIN_DIRS=()
          if [[ -n "$ALL_PACKAGE_DIRS" ]]; then
            for pkg_dir in $ALL_PACKAGE_DIRS; do
              if echo "${CHANGED_FILES}" | grep -q -E "^${pkg_dir}/"; then
                VALID_PLUGIN_DIRS+=("$pkg_dir")
              fi
            done
          fi
          if [ ${#VALID_PLUGIN_DIRS[@]} -eq 0 ]; then
            echo "plugins=[]" >> $GITHUB_OUTPUT
          else
            JSON_ARRAY=$(printf '%s\n' "${VALID_PLUGIN_DIRS[@]}" | jq -R . | jq -sc .)
            echo "plugins=${JSON_ARRAY}" >> $GITHUB_OUTPUT
          fi

  build-workspace:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_plugins != '[]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Ativar Corepack para usar a versão correta do Yarn
        run: corepack enable
        
      - name: Instalar Dependências
        run: yarn install --immutable

      - name: Construir todo o monorepo
        run: |
          yarn tsc
          yarn build:all
      - name: Carregar artefatos de build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .
            !node_modules/**

  publish-plugins:
    needs: [detect-changes, build-workspace]
    if: needs.detect-changes.outputs.changed_plugins != '[]'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        plugin_dir: ${{ fromJson(needs.detect-changes.outputs.changed_plugins) }}

    steps:
      - name: Configurar Node.js e Autenticação NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Ativar Corepack para usar a versão correta do Yarn
        run: corepack enable

      - name: Baixar artefatos de build
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      
      - name: Instalar Dependências de Produção
        run: yarn install --immutable --production

      - name: Publicar no NPM (${{ matrix.plugin_dir }})
        run: npm publish --access public
        working-directory: ${{ matrix.plugin_dir }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}