# .github/workflows/publish-plugin.yml

name: Detect Changes and Publish Plugins to NPM

on:
  push:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed_plugins: ${{ steps.filter_changes.outputs.plugins }}

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identificar e filtrar plugins válidos alterados
        id: filter_changes
        run: |
          # Etapa 1: Obter a lista de todos os arquivos alterados
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "Nova branch ou primeiro push. Verificando todos os arquivos rastreados."
            CHANGED_FILES=$(git ls-files)
          else
            echo "Push em branch existente. Comparando commits."
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
          
          echo -e "\nArquivos alterados detectados:\n${CHANGED_FILES}"

          # Etapa 2: Extrair os diretórios raiz únicos dos plugins alterados
          CHANGED_PLUGIN_DIRS=$(echo "${CHANGED_FILES}" | grep -E '^plugins/' | sed -E 's|^(plugins/[^/]+)/.*|\1|' | sort -u)

          # --- LÓGICA PRINCIPAL ---
          # Etapa 3: Verificar quais dos diretórios alterados realmente contêm um 'package.json'
          VALID_PLUGIN_DIRS=()
          if [[ -n "$CHANGED_PLUGIN_DIRS" ]]; then
              for dir in $CHANGED_PLUGIN_DIRS; do
                  # Verifica se o arquivo package.json existe no diretório
                  if [ -f "${dir}/package.json" ]; then
                      VALID_PLUGIN_DIRS+=("$dir")
                  else
                      echo "-> Ignorando '${dir}': 'package.json' não encontrado."
                  fi
              done
          fi

          # Etapa 4: Gerar o output JSON apenas com os plugins válidos
          if [ ${#VALID_PLUGIN_DIRS[@]} -eq 0 ]; then
              echo -e "\nNenhum plugin válido (com package.json) foi alterado."
              echo "plugins=[]" >> $GITHUB_OUTPUT
          else
              echo -e "\nPlugins válidos para publicação:"
              printf '%s\n' "${VALID_PLUGIN_DIRS[@]}"
              
              # Converte o array bash para um array JSON para o próximo job
              JSON_ARRAY=$(printf '%s\n' "${VALID_PLUGIN_DIRS[@]}" | jq -R . | jq -sc .)
              echo "plugins=${JSON_ARRAY}" >> $GITHUB_OUTPUT
          fi

  publish-plugins:
    needs: detect-changes
    if: fromJson(needs.detect-changes.outputs.changed_plugins) != '[]'

    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        plugin_dir: ${{ fromJson(needs.detect-changes.outputs.changed_plugins) }}

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js e Autenticação NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Instalar Dependências
        run: yarn install --frozen-lockfile

      - name: Gerar Arquivos de Definição de Tipos (.d.ts)
        run: yarn tsc

      - name: Construir o Plugin (${{ matrix.plugin_dir }})
        run: yarn --cwd ${{ matrix.plugin_dir }} build

      - name: Publicar no NPM (${{ matrix.plugin_dir }})
        run: npm publish --access public
        working-directory: ${{ matrix.plugin_dir }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}